---
- hosts: WindowsHosts

  tasks:
  - name: install windows updates
    win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
        - UpdateRollups
        - ServicePacks
        - FeaturePacks
      reboot: yes
      reboot_timeout: 420